Update patch set 1
Patch Set 1:

This patch is somehow already in master, although it says not merged here.

But it broke the build; please fix:

UnitWOPIRenameFile.cpp: In member function ‘virtual void UnitWOPIRenameFile::invokeTest()’:
UnitWOPIRenameFile.cpp:66:41: error: ‘std::unique_ptr<UnitWebSocket> WopiTestServer::_ws’ is private within this context
                 helpers::sendTextFrame(*_ws->getLOOLWebSocket(), "load url=" + _wopiSrc, testName);
                                         ^~~
In file included from UnitWOPIRenameFile.cpp:12:
./WopiTestServer.hpp:38:36: note: declared private here
     std::unique_ptr<UnitWebSocket> _ws;
                                    ^~~
UnitWOPIRenameFile.cpp:66:80: error: ‘std::__cxx11::string WopiTestServer::_wopiSrc’ is private within this context
                 helpers::sendTextFrame(*_ws->getLOOLWebSocket(), "load url=" + _wopiSrc, testName);
                                                                                ^~~~~~~~
In file included from UnitWOPIRenameFile.cpp:12:
./WopiTestServer.hpp:35:17: note: declared private here
     std::string _wopiSrc;
                 ^~~~~~~~
UnitWOPIRenameFile.cpp:72:41: error: ‘std::unique_ptr<UnitWebSocket> WopiTestServer::_ws’ is private within this context
                 helpers::sendTextFrame(*_ws->getLOOLWebSocket(), "renamefile filename=hello", testName);
                                         ^~~
In file included from UnitWOPIRenameFile.cpp:12:
./WopiTestServer.hpp:38:36: note: declared private here
     std::unique_ptr<UnitWebSocket> _ws;
                                    ^~~

Patch-set: 1
Reviewer: Gerrit User 1000166 <1000166@6622c302-437a-49ad-a91d-55ba7dcf1615>
Label: Verified=0