Update patch set 1
Patch Set 1:

Hello,

This patch is to replace uglify-js with terser. I remember your suggestion to just update uglify-js. But i got this error with the update:

Uglify loleaflet js files...
Parse error at /home/collabora/jenkins/workspace/gerrit_online_master/loleaflet/build/bundle.js:41541,8
        const fs = require('fs');
        ^
ERROR: Unexpected token: keyword «const»

So i replaced it with terser. Can you review the patch?

Thank you.

Patch-set: 1
Reviewer: Gerrit User 1000865 <1000865@6622c302-437a-49ad-a91d-55ba7dcf1615>
CC: Gerrit User 1000028 <1000028@6622c302-437a-49ad-a91d-55ba7dcf1615>
Reviewer: Gerrit User 1002314 <1002314@6622c302-437a-49ad-a91d-55ba7dcf1615>