Revert "loleaflet: move the code about initialization of the style combobox"
Breaks mobile view in Impress.
TypeError: Cannot read property 'length' of undefined

This reverts commit 9db6f855a016891f5c0d59cab014f246752cd907.

Change-Id: I839cde8bb683fc0b933da806f4a4771114eb32f5