Update patch set 1
Patch Set 1:

> Patch Set 1:
>         ^
> ERROR: Unexpected token: keyword «const»
> 
> So i replaced it with terser. Can you review the patch?

This is a problem on its own, because const is an ES6 declaration, and IE11 does not support ES6 and we try to support IE11. Where is it coming from?

Patch-set: 1