test: avoid variable-sized object initialization
UnitHTTP.cpp:94:21: error: variable-sized object may not be initialized
        char buffer[str.size() + 64] = { 0, };
                    ^~~~~~~~~~~~~~~

(cherry picked from commit 66fff0e8a9df7b8c4dc46f53e5154845eb951aa5)

Change-Id: I2e6c8b4ca123ac5bf6391aa460069d24066f728d