android: fix missing brand resource
configured with no brand and I get the following error:

./gradlew assemble

: error: cannot find symbol
        builder .setIcon(BuildConfig.APP_HAS_BRANDING? R.drawable.ic_launcher_brand: R.drawable.lo_icon)
  symbol:   variable ic_launcher_brand
  location: class drawable

Change-Id: Ibf3dcf581f12190ba4664b286710fc5a8ef43fe2